name: CI-Test

on:
    pull_request:
        branches:
            - develop
            - release
            - release/*

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.17.3
            - run: yarn install --frozen-lockfile
            - name: Run unit tests with coverage
              env:
                  XXX: 1
              run: yarn test
